In this assignement, feel free to use the `sparse` module from `scipy`.

Use the cell below for your imports.

In [40]:
from scipy.sparse import csr_matrix
import numpy as np
import scipy.sparse as sp

implement the function `mat_mul_coo` that takes two sparse matrices in `coo` and returns their product.

In [14]:
import numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse import csr_matrix

def mat_mul_coo(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Incompatible shapes")

    A_coo = coo_matrix(A)
    B_coo = coo_matrix(B)

    rows = []
    cols = []
    vals = []

    for i, j, a in zip(A_coo.row, A_coo.col, A_coo.data):
        for k, l, b in zip(B_coo.row, B_coo.col, B_coo.data):
            if j == k:
                rows.append(i)
                cols.append(l)
                vals.append(a * b)

    C = coo_matrix((vals, (rows, cols)), shape=(A.shape[0], B.shape[1]))
    return csr_matrix(C)

In [15]:
A = np.array([[0, 1, 0], [2, 0, 3], [0, 4, 0]])
B = np.array([[5, 0, 6], [0, 7, 0], [8, 0, 9]])

print("A:")
print(A)
print("B:")
print(B)

C = mat_mul_coo(A, B)
print("C:")
print(C.toarray())

A:
[[0 1 0]
 [2 0 3]
 [0 4 0]]
B:
[[5 0 6]
 [0 7 0]
 [8 0 9]]
C:
[[ 0  7  0]
 [34  0 39]
 [ 0 28  0]]


implement the function `mat_mul_csr` that takes two sparse matrices in `csr` format and returns their product.

In [27]:
import numpy as np
from scipy.sparse import csr_matrix

def mat_mul_csr(A, B):
 
    data1, col_indice1, row_pointers1 = A
    data2, col_indice2, row_pointers2 = B
    
    spcsr1 = csr_matrix((data1, col_indice1, row_pointers1))
    spcsr2 = csr_matrix((data2, col_indice2, row_pointers2))
    
    multi_csr = csr_matrix(spcsr1.dot(spcsr2))
    
    data = multi_csr.data
    col_indice = multi_csr.indices
    row_pointers = multi_csr.indptr
    
    return (data, col_indice, row_pointers)

In [29]:
A = ([1, 2, 3, 4, 5], [0, 0, 1, 1, 2], [0, 2, 2, 4])
B = ([1, 2, 3, 4], [0, 1, 1, 2], [0, 2, 3, 4])

result = mat_mul_csr(A, B)
result

(array([ 6,  3, 21], dtype=int32),
 array([1, 0, 1], dtype=int32),
 array([0, 2, 2, 3], dtype=int32))

implement a function `solve_lin_sys` that takes a matrix `A` in `csr` format and a vector `b` as a numpy array and solves the system `Ax = b`.

In [46]:
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import spsolve

def solve_lin_sys(A, b):
    """
    Solves the linear system Ax = b, where A is a matrix in csr format and b is a vector.
    Returns the solution vector x.
    """
    x = spsolve(csr_matrix(A), b)
    return x

In [47]:
A = sp.csr_matrix([[1, 2, 0], [0, 3, 4], [5, 0, 6]])
b = np.array([6, 7, 8])
x = solve_lin_sys(A, b)
print(x)

[1.51724138 2.24137931 0.06896552]
